"""Full-catalog lexical search used by the website baseline."""

from .index import (
    CATALOG_SCHEMA_VERSION,
    DEFAULT_CATALOG_INDEX,
    EXPECTED_PRODUCT_COUNT,
    CatalogIndexMetadata,
    build_catalog_index,
)
from .index_v2 import (
    CATALOG_V2_INDEX_CONFIG,
    CATALOG_V2_SCHEMA_VERSION,
    DEFAULT_CATALOG_V2_INDEX,
    CatalogIndexV2Metadata,
    CatalogV2IndexMetadata,
    build_catalog_index_v2,
)
from .pipeline_v2 import (
    PRODUCTION_PIPELINE_CONFIG,
    PRODUCTION_PIPELINE_CONFIG_SHA256,
    PRODUCTION_PIPELINE_ID,
    PRODUCTION_STRATEGY_ID,
    CatalogV2Product,
    CatalogV2SearchPipeline,
    ProductionPipelineHit,
    ProductionPipelineResult,
    validate_production_pipeline_config,
)
from .search import (
    CatalogBatchSearchFailed,
    CatalogProduct,
    CatalogSearchDeadlineExceeded,
    CatalogSearchHit,
    CatalogSearchResult,
    CatalogSearchService,
    InvalidCatalogQuery,
    validate_catalog_query,
)
from .serving import (
    ActiveCatalogSearchResult,
    ActiveCatalogSearchService,
    CatalogServingService,
    RetrievalActivationRejected,
    RetrievalRollbackRejected,
    RetrievalServingConfigurationError,
    RetrievalServingError,
    RetrievalServingState,
    RetrievalStrategyResolver,
    load_active_retrieval_revision,
    load_retrieval_serving_state,
    rollback_retrieval_strategy,
    validate_and_activate_retrieval_strategy,
)

__all__ = [
    "CATALOG_SCHEMA_VERSION",
    "CATALOG_V2_INDEX_CONFIG",
    "CATALOG_V2_SCHEMA_VERSION",
    "DEFAULT_CATALOG_INDEX",
    "DEFAULT_CATALOG_V2_INDEX",
    "EXPECTED_PRODUCT_COUNT",
    "PRODUCTION_PIPELINE_CONFIG",
    "PRODUCTION_PIPELINE_CONFIG_SHA256",
    "PRODUCTION_PIPELINE_ID",
    "PRODUCTION_STRATEGY_ID",
    "ActiveCatalogSearchResult",
    "ActiveCatalogSearchService",
    "CatalogServingService",
    "CatalogIndexMetadata",
    "CatalogIndexV2Metadata",
    "CatalogProduct",
    "CatalogV2IndexMetadata",
    "CatalogV2Product",
    "CatalogV2SearchPipeline",
    "CatalogBatchSearchFailed",
    "CatalogSearchHit",
    "CatalogSearchResult",
    "CatalogSearchService",
    "CatalogSearchDeadlineExceeded",
    "InvalidCatalogQuery",
    "ProductionPipelineHit",
    "ProductionPipelineResult",
    "RetrievalActivationRejected",
    "RetrievalRollbackRejected",
    "RetrievalServingConfigurationError",
    "RetrievalServingError",
    "RetrievalServingState",
    "RetrievalStrategyResolver",
    "build_catalog_index",
    "build_catalog_index_v2",
    "load_active_retrieval_revision",
    "load_retrieval_serving_state",
    "rollback_retrieval_strategy",
    "validate_catalog_query",
    "validate_and_activate_retrieval_strategy",
    "validate_production_pipeline_config",
]
